  - name: "Install packages - Required for apt over HTTPS"
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
      install_recommends: false
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    tags:
      - configure
      - install
      - prepare
