
stages:
    - validation
    - release
    - sync
    - publish

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible-roles.git"
    
    MY_PROJECT_ID: "28204898"
    NFC_GITLAB_SUBMODULE_HASH: '$(git submodule status --recursive | awk "{print $$1}")'
    NFC_GITLAB_CI_URL: "https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/$NFC_GITLAB_SUBMODULE_HASH"


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - conventional_commits/.gitlab-ci.yml
      - gitlab_release/.gitlab-ci.yml
      - git_push_mirror/.gitlab-ci.yml
      #- ansible/.gitlab-ci.yml


Gitlab Release:
    extends:
        - .gitlab_release


Github (Push --mirror):
    extends:
        - .git_push_mirror


ansible-ee Container:
  stage: publish
  trigger:
    project: nofusscomputing/projects/ansible/execution_environment
    branch: development
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
    - when: never