
stages:
    - validation
    - release
    - sync

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MY_PROJECT_ID: "28204898"


include:
  - local: CI/ansible/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/conventional_commits/.gitlab-ci.yml
  - local: CI/gitlab_release/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/git_push_mirror/.gitlab-ci.yml


Github (Push --mirror):
    variables:
        GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/gitlab-ci.git"
    extends:
        - .git_push_mirror

