
stages:
    - validation
    - release
    - sync

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MY_PROJECT_ID: "28204898"
    NFC_GITLAB_SUBMODULE_HASH: 'git submodule status --recursive | awk "{print $$1}"'
    NFC_GITLAB_CI_URL: "https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/$NFC_GITLAB_SUBMODULE_HASH"


include:
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/eb5cc8a0e2885a9ed16a8d1a81611aec4d5a4d31/conventional_commits/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/eb5cc8a0e2885a9ed16a8d1a81611aec4d5a4d31/gitlab_release/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/eb5cc8a0e2885a9ed16a8d1a81611aec4d5a4d31/git_push_mirror/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/eb5cc8a0e2885a9ed16a8d1a81611aec4d5a4d31/ansible/.gitlab-ci.yml


Ansible Lint (python 3.6):
    variables:
        ANSIBLE_LINT_PATH: "roles/"
    extends:
        - .ansible_linter_defaults
    image: python:3.6-slim


Github (Push --mirror):
    variables:
        GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/gitlab-ci.git"
    extends:
        - .git_push_mirror

