
stages:
    - validation
    - release
    - sync

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MY_PROJECT_ID: "28204898"


include:
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/conventional_commits/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/gitlab_release/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/git_push_mirror/.gitlab-ci.yml
  - remote: https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/development/ansible/.gitlab-ci.yml


Ansible Lint (python 3.6):
    variables:
        ANSIBLE_LINT_PATH: "roles/"
    extends:
        - .ansible_linter_defaults
    image: python:3.6-slim


Github (Push --mirror):
    variables:
        GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/gitlab-ci.git"
    extends:
        - .git_push_mirror

