
stages:
    - validation
    - release
    - sync

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MY_PROJECT_ID: "28204898"
    NFC_GITLAB_SUBMODULE_HASH: '$(git submodule status --recursive | awk "{print $$1}")'
    NFC_GITLAB_CI_URL: "https://gitlab.com/nofusscomputing/projects/gitlab-ci/-/raw/$NFC_GITLAB_SUBMODULE_HASH"


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - conventional_commits/.gitlab-ci.yml
      - gitlab_release/.gitlab-ci.yml
      - git_push_mirror/.gitlab-ci.yml
      - ansible/.gitlab-ci.yml


Ansible Lint (python 3.11):
    variables:
        ANSIBLE_LINT_PATH: "roles/"
    extends:
        - .ansible_linter_defaults
    image: python:3.11-slim


Gitlab Release:
    extends:
        - .gitlab_release


Github (Push --mirror):
    variables:
        GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible-roles.git"
    extends:
        - .git_push_mirror

