---

- name: Initial playbook setup
  ansible.builtin.include_tasks:
    file: initial.yaml
  when: not initial_common_tasks | default(false) | bool
  tags:
    - always


# As this role is to be included in playbooks with ``, this will gather the facts for the play
- name: Gather facts
  ansible.builtin.gather_facts:
  when: common_gather_facts | bool
  tags:
    - always


#
#  Common functions
#

- name: Create Apt proxy configuration file
  ansible.builtin.template:
    src: 'apt_proxy.conf'
    dest: '/etc/apt/apt.conf.d/apt_proxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: >
    apt_proxy_url is defined
      and
    apt_proxy_url | default('')| length | int > 0


- name: Create Apt proxy configuration file
  ansible.builtin.file:
    name: '/etc/apt/apt.conf.d/apt_proxy.conf'
    state: absent
  when: >
    apt_proxy_url is defined
      and
    apt_proxy_url | default('')| length | int == 0


- name: APT Repositories
  ansible.builtin.include_tasks: apt_repository.yaml
  when: >
    aptRepositories is defined
      and
    aptRepositories | default('') | length | int > 0


- name: APT Installation
  ansible.builtin.include_tasks: apt_install.yaml
  when: >
    aptInstall is defined
      and
    aptInstall | default('') | length > 0


- name: Template Filez
  ansible.builtin.include_tasks: template.yaml
  when: files.templates is defined
#      and
#    files.templates | default ('') | length | int > 0
