  - name: "export variables for use in other roles"
    set_fact:
      directory_homeassistant_config_root: "{{ directory_homeassistant_config_root }}"
      directory_homeassistant_logs:  "{{ directory_homeassistant_logs }}"
    tags:
      - configure
      - install
      - prepare


  - name: "Create OS Group {{ docker_container_user_homeassistant }}"
    group:
      name: "{{ docker_container_user_homeassistant }}"
      state: present
    tags:
      - configure
      - install


  - name: "Create OS User {{ docker_container_user_homeassistant }}"
    user:
      name: "{{ docker_container_user_homeassistant }}"
      group: "{{ docker_container_user_homeassistant }}"
      state: present
      shell: "/bin/bash"
    tags:
      - configure
      - install


  - name: "Pull Docker Image {{ docker_image_homeassistant }}:{{ docker_image_homeassistant_tag }}"
    docker_image:
      name: "{{ docker_image_homeassistant }}:{{ docker_image_homeassistant_tag }}"
      source: pull
    tags:
      - configure
      - install
      - prepare


  - name: "Create Docker Network"
    docker_network:
      name: "{{ docker_network_homeassistant }}"
      internal: no
      state: present
    tags:
      - configure
      - install


  - name: Create Required Directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ docker_container_user_homeassistant }}"
      group: "{{ docker_container_user_homeassistant }}"
      mode: '0750'
    with_items:
      - "{{ directory_homeassistant_config_root }}"
      - "{{ directory_homeassistant_logs }}"
    tags:
      - configure
      - install


  - name: Create Docker Container - [{{ docker_container_name_homeassistant }}] with published ports
    docker_container:
      name: "{{ docker_container_name_homeassistant }}"
      image: "{{ docker_image_homeassistant }}:{{ docker_image_homeassistant_tag }}"
      memory: "{{ docker_container_homeassistant_memory }}"
      cpuset_cpus: "{{ docker_container_homeassistant_cpu_set }}"
      comparisons: 
        '*': ignore
        image: strict
        env: strict
        user: strict
        published_ports: strict
        volumes: allow_more_present
        networks: allow_more_present
      state: started
      restart_policy: always
      published_ports: "{{ docker_container_homeassistant_published_ports }}"
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - "{{ directory_homeassistant_config_root }}:/config"
        - "{{ directory_homeassistant_logs }}:/var/log/nginx:rw"
      networks_cli_compatible: yes
      networks:
        - name: "{{ docker_network_homeassistant }}"
#      user: "{{ nginx_uid.stdout }}"
    register: "docker_container_homeassistant"
    when: docker_container_homeassistant_published_ports is defined
    tags:
      - install


  - name: Create Docker Container - [{{ docker_container_name_homeassistant }}]
    docker_container:
      name: "{{ docker_container_name_homeassistant }}"
      image: "{{ docker_image_homeassistant }}:{{ docker_image_homeassistant_tag }}"
      memory: "{{ docker_container_homeassistant_memory }}"
      cpuset_cpus: "{{ docker_container_homeassistant_cpu_set }}"
      comparisons: 
        '*': ignore
        image: strict
        env: strict
        user: strict
        exposed_ports: strict
        volumes: allow_more_present
        networks: allow_more_present
      state: started
      restart_policy: always
      exposed_ports: "{{ docker_container_homeassistant_exposed_ports }}"
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - "{{ directory_homeassistant_config_root }}:/config"
        - "{{ directory_homeassistant_logs }}:/var/log/nginx:rw"
      networks_cli_compatible: yes
      networks:
        - name: "{{ docker_network_homeassistant }}"
#      user: "{{ nginx_uid.stdout }}"
    register: "docker_container_nginx"
    when: docker_container_homeassistant_published_ports is not defined
    tags:
      - install


  - name: "logrotate Configuration"
    template:
      src: logroate_nginx.j2
      dest: "/etc/logrotate.d/homeassistant_{{ docker_container_name_homeassistant }}"
      owner: root
      mode: 0640
      force: yes
    notify: "Restart logrotate"
    tags:
      - configure
      - install


#  - name: "Fail2Ban Jail for {{ docker_container_name_nginx }}"
#    template:
#      src: fail2ban_jail_nginx_default.conf.j2
#      dest: "{{ directory_fail2ban_config }}/jail.d/nginx_{{ docker_container_name_nginx }}.local"
#      owner: root
#      mode: 0600
#      force: yes
#    notify: "Restart fail2ban"
#    tags:
#      - configure
#      - install


#########################################
# Remove the role
#########################################

  - name: Remove Docker Container - [{{ docker_container_name_homeassistant }}]
    docker_container:
      name: "{{ docker_container_name_homeassistant }}"
      state: absent
    tags:
      - remove
      - never


  - name: "Remove OS User {{ docker_container_user_homeassistant }}"
    user:
      name: "{{ docker_container_user_homeassistant }}"
      group: "{{ docker_container_user_homeassistant }}"
      state: absent
    tags:
      - clean
      - never


  - name: "Remove OS Group {{ docker_container_user_homeassistant }}"
    group:
      name: "{{ docker_container_user_homeassistant }}"
      state: absent
    tags:
      - clean
      - never


  - name: "Remove Docker Image {{ docker_image_homeassistant }}:{{ docker_image_nhomeassistant_tag }}"
    docker_image:
      name: "{{ docker_image_homeassistant }}:{{ docker_image_homeassistant_tag }}"
      state: absent
    tags:
      - clean
      - never


  - name: "Remove Docker Network"
    docker_network:
      name: "{{ docker_network_homeassistant }}"
      state: absent
    tags:
      - clean
      - never


  - name: Remove Directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ directory_homeassistant_config_root }}"
      - "{{ directory_homeassistant_logs }}"
    tags:
      - clean
      - never

  - name: "logrotate Configuration"
    file:
      path: "/etc/logrotate.d/homeassistant_{{ docker_container_name_homeassistant }}"
      state: absent
    notify: "Restart logrotate"
    tags:
      - clean
      - remove
      - never


#  - name: "Fail2Ban Jail for {{ docker_container_name_nginx }}"
#    file:
#      path: "{{ directory_fail2ban_config }}/jail.d/nginx_{{ docker_container_name_nginx }}.local"
#      state: absent
#    notify: "Restart fail2ban"
#    tags:
#      - clean
#      - remove
#      - never
