
  - name: "Install logrotate"
    apt:
      name: "logrotate"
      state: present
      update_cache: yes
      install_recommends: false
    register: logrotate_installed
    tags:
      - install






