---
- name: Log Rotate Configuration files
  ansible.builtin.set_fact:
    logrotate_configuration: "{{ logrotate_configuration + [item] }}"
  loop: "{{ logrotate | default([]) }}"


- name: Logrotate configuration notify
  ansible.builtin.assert:
    msg: logrotate will be configured
    that:
      - logrotate_configuration | length | int > 0
  # loop: "{{ logrotate }}"
  notify: 'configure_logrotate'
  changed_when: true
  when: logrotate_configuration | length | int > 0


- name: Clear logrotate configure task variables
  ansible.builtin.set_fact:
    logrotate: []

- name: Reload logroate if required
  ansible.builtin.meta: flush_handlers
